/*
 * Deel REST API
 * API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContractToCreateSharedClientLegalEntity;
import com.konfigthis.client.model.ContractToCreateSharedClientTeam;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ContractToCreateSharedClient
 */
public class ContractToCreateSharedClientTest {
    private final ContractToCreateSharedClient model = new ContractToCreateSharedClient();

    /**
     * Model tests for ContractToCreateSharedClient
     */
    @Test
    public void testContractToCreateSharedClient() {
        // TODO: test ContractToCreateSharedClient
    }

    /**
     * Test the property 'legalEntity'
     */
    @Test
    public void legalEntityTest() {
        // TODO: test legalEntity
    }

    /**
     * Test the property 'team'
     */
    @Test
    public void teamTest() {
        // TODO: test team
    }

}
