/*
 * Deel REST API
 * API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeTimeoffsEntitlementsItem
 */
public class EmployeeTimeoffsEntitlementsItemTest {
    private final EmployeeTimeoffsEntitlementsItem model = new EmployeeTimeoffsEntitlementsItem();

    /**
     * Model tests for EmployeeTimeoffsEntitlementsItem
     */
    @Test
    public void testEmployeeTimeoffsEntitlementsItem() {
        // TODO: test EmployeeTimeoffsEntitlementsItem
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'trackingPeriod'
     */
    @Test
    public void trackingPeriodTest() {
        // TODO: test trackingPeriod
    }

    /**
     * Test the property 'vacationAllowed'
     */
    @Test
    public void vacationAllowedTest() {
        // TODO: test vacationAllowed
    }

    /**
     * Test the property 'vacationRollover'
     */
    @Test
    public void vacationRolloverTest() {
        // TODO: test vacationRollover
    }

    /**
     * Test the property 'vacationExpired'
     */
    @Test
    public void vacationExpiredTest() {
        // TODO: test vacationExpired
    }

    /**
     * Test the property 'vacationPayout'
     */
    @Test
    public void vacationPayoutTest() {
        // TODO: test vacationPayout
    }

    /**
     * Test the property 'vacationRequested'
     */
    @Test
    public void vacationRequestedTest() {
        // TODO: test vacationRequested
    }

    /**
     * Test the property 'vacationApproved'
     */
    @Test
    public void vacationApprovedTest() {
        // TODO: test vacationApproved
    }

    /**
     * Test the property 'vacationUsed'
     */
    @Test
    public void vacationUsedTest() {
        // TODO: test vacationUsed
    }

    /**
     * Test the property 'vacationTotal'
     */
    @Test
    public void vacationTotalTest() {
        // TODO: test vacationTotal
    }

    /**
     * Test the property 'sickLeaveRequested'
     */
    @Test
    public void sickLeaveRequestedTest() {
        // TODO: test sickLeaveRequested
    }

    /**
     * Test the property 'sickLeaveApproved'
     */
    @Test
    public void sickLeaveApprovedTest() {
        // TODO: test sickLeaveApproved
    }

    /**
     * Test the property 'sickLeaveUsed'
     */
    @Test
    public void sickLeaveUsedTest() {
        // TODO: test sickLeaveUsed
    }

    /**
     * Test the property 'sickLeaveTotal'
     */
    @Test
    public void sickLeaveTotalTest() {
        // TODO: test sickLeaveTotal
    }

    /**
     * Test the property 'sickLeaveAllowed'
     */
    @Test
    public void sickLeaveAllowedTest() {
        // TODO: test sickLeaveAllowed
    }

    /**
     * Test the property 'otherLeaveRequested'
     */
    @Test
    public void otherLeaveRequestedTest() {
        // TODO: test otherLeaveRequested
    }

    /**
     * Test the property 'otherLeaveApproved'
     */
    @Test
    public void otherLeaveApprovedTest() {
        // TODO: test otherLeaveApproved
    }

    /**
     * Test the property 'otherLeaveUsed'
     */
    @Test
    public void otherLeaveUsedTest() {
        // TODO: test otherLeaveUsed
    }

    /**
     * Test the property 'otherLeaveTotal'
     */
    @Test
    public void otherLeaveTotalTest() {
        // TODO: test otherLeaveTotal
    }

}
