/*
 * Deel REST API
 * API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmployeeListClientLegalEntity;
import com.konfigthis.client.model.EmployeeListMonthlyPayment;
import com.konfigthis.client.model.EmployeeListPaymentsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeList
 */
public class EmployeeListTest {
    private final EmployeeList model = new EmployeeList();

    /**
     * Model tests for EmployeeList
     */
    @Test
    public void testEmployeeList() {
        // TODO: test EmployeeList
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'personalEmail'
     */
    @Test
    public void personalEmailTest() {
        // TODO: test personalEmail
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'picUrl'
     */
    @Test
    public void picUrlTest() {
        // TODO: test picUrl
    }

    /**
     * Test the property 'hiringType'
     */
    @Test
    public void hiringTypeTest() {
        // TODO: test hiringType
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'team'
     */
    @Test
    public void teamTest() {
        // TODO: test team
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'payments'
     */
    @Test
    public void paymentsTest() {
        // TODO: test payments
    }

    /**
     * Test the property 'hourlyReportTotal'
     */
    @Test
    public void hourlyReportTotalTest() {
        // TODO: test hourlyReportTotal
    }

    /**
     * Test the property 'clientLegalEntity'
     */
    @Test
    public void clientLegalEntityTest() {
        // TODO: test clientLegalEntity
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'seniority'
     */
    @Test
    public void seniorityTest() {
        // TODO: test seniority
    }

    /**
     * Test the property 'completionDate'
     */
    @Test
    public void completionDateTest() {
        // TODO: test completionDate
    }

    /**
     * Test the property 'hiringStatus'
     */
    @Test
    public void hiringStatusTest() {
        // TODO: test hiringStatus
    }

    /**
     * Test the property 'monthlyPayment'
     */
    @Test
    public void monthlyPaymentTest() {
        // TODO: test monthlyPayment
    }

}
