/*
 * Deel REST API
 * API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GPContractCreatedEmploymentHolidays
 */
public class GPContractCreatedEmploymentHolidaysTest {
    private final GPContractCreatedEmploymentHolidays model = new GPContractCreatedEmploymentHolidays();

    /**
     * Model tests for GPContractCreatedEmploymentHolidays
     */
    @Test
    public void testGPContractCreatedEmploymentHolidays() {
        // TODO: test GPContractCreatedEmploymentHolidays
    }

    /**
     * Test the property 'allowance'
     */
    @Test
    public void allowanceTest() {
        // TODO: test allowance
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

}
