/*
 * Deel REST API
 * API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.HrisCompensation;
import com.konfigthis.client.model.HrisDirectEmployeeDetails;
import com.konfigthis.client.model.HrisDirectEmployeeVacationInfo;
import com.konfigthis.client.model.HrisTeamInformation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HrisDirectEmployee
 */
public class HrisDirectEmployeeTest {
    private final HrisDirectEmployee model = new HrisDirectEmployee();

    /**
     * Model tests for HrisDirectEmployee
     */
    @Test
    public void testHrisDirectEmployee() {
        // TODO: test HrisDirectEmployee
    }

    /**
     * Test the property 'employeeDetails'
     */
    @Test
    public void employeeDetailsTest() {
        // TODO: test employeeDetails
    }

    /**
     * Test the property 'teamInformation'
     */
    @Test
    public void teamInformationTest() {
        // TODO: test teamInformation
    }

    /**
     * Test the property 'jobInformation'
     */
    @Test
    public void jobInformationTest() {
        // TODO: test jobInformation
    }

    /**
     * Test the property 'compensation'
     */
    @Test
    public void compensationTest() {
        // TODO: test compensation
    }

    /**
     * Test the property 'contract'
     */
    @Test
    public void contractTest() {
        // TODO: test contract
    }

    /**
     * Test the property 'vacationInfo'
     */
    @Test
    public void vacationInfoTest() {
        // TODO: test vacationInfo
    }

}
