/*
 * Deel REST API
 * API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkerTerminationBody
 */
public class WorkerTerminationBodyTest {
    private final WorkerTerminationBody model = new WorkerTerminationBody();

    /**
     * Model tests for WorkerTerminationBody
     */
    @Test
    public void testWorkerTerminationBody() {
        // TODO: test WorkerTerminationBody
    }

    /**
     * Test the property 'desiredEndDate'
     */
    @Test
    public void desiredEndDateTest() {
        // TODO: test desiredEndDate
    }

    /**
     * Test the property 'lastDateOfWork'
     */
    @Test
    public void lastDateOfWorkTest() {
        // TODO: test lastDateOfWork
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'isVoluntary'
     */
    @Test
    public void isVoluntaryTest() {
        // TODO: test isVoluntary
    }

    /**
     * Test the property 'severance'
     */
    @Test
    public void severanceTest() {
        // TODO: test severance
    }

}
