/*
 * Deel REST API
 * API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Type of a contract
 */
@JsonAdapter(ContractTypeEnum.Adapter.class)public enum ContractTypeEnum {
  
  ONGOING_TIME_BASED("ongoing_time_based"),
  
  MILESTONES("milestones"),
  
  TIME_BASED("time_based"),
  
  PAY_AS_YOU_GO_TIME_BASED("pay_as_you_go_time_based"),
  
  COMMISSION("commission"),
  
  PAYG_MILESTONES("payg_milestones"),
  
  PAYG_TASKS("payg_tasks"),
  
  EOR("eor"),
  
  UNKNOWN("unknown"),
  
  EMPLOYEE("employee"),
  
  GLOBAL_PAYROLL("global_payroll"),
  
  SHIELD_MSA("shield_msa"),
  
  HRIS_DIRECT_EMPLOYEE("hris_direct_employee");

  private String value;

  ContractTypeEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ContractTypeEnum fromValue(String value) {
    for (ContractTypeEnum b : ContractTypeEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ContractTypeEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final ContractTypeEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ContractTypeEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ContractTypeEnum.fromValue(value);
    }
  }
}

