/*
 * Deel REST API
 * API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WeekDaysEnum;
import com.konfigthis.client.model.WorkStatementCycleEndTypeEnum;
import com.konfigthis.client.model.WorkStatementCycleScaleEnum;
import com.konfigthis.client.model.WorkStatementPaymentDueTypeEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * EstimateFirstPaymentCompensationDetails
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EstimateFirstPaymentCompensationDetails {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private Double amount;

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "currency_code";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public static final String SERIALIZED_NAME_SCALE = "scale";
  @SerializedName(SERIALIZED_NAME_SCALE)
  private WorkStatementCycleScaleEnum scale;

  public static final String SERIALIZED_NAME_CYCLE_END = "cycle_end";
  @SerializedName(SERIALIZED_NAME_CYCLE_END)
  private Double cycleEnd;

  public static final String SERIALIZED_NAME_CYCLE_END_TYPE = "cycle_end_type";
  @SerializedName(SERIALIZED_NAME_CYCLE_END_TYPE)
  private WorkStatementCycleEndTypeEnum cycleEndType;

  public static final String SERIALIZED_NAME_PAYMENT_DUE_TYPE = "payment_due_type";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DUE_TYPE)
  private WorkStatementPaymentDueTypeEnum paymentDueType = WorkStatementPaymentDueTypeEnum.REGULAR;

  public static final String SERIALIZED_NAME_PAYMENT_DUE_DAYS = "payment_due_days";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DUE_DAYS)
  private Double paymentDueDays;

  /**
   * Either works days or calendar days
   */
  @JsonAdapter(CalculationTypeEnum.Adapter.class)
 public enum CalculationTypeEnum {
    CUSTOM_AMOUNT("CUSTOM_AMOUNT"),
    
    WORK_DAYS("WORK_DAYS"),
    
    CALENDAR_DAYS("CALENDAR_DAYS"),
    
    FULL_AMOUNT("FULL_AMOUNT");

    private String value;

    CalculationTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CalculationTypeEnum fromValue(String value) {
      for (CalculationTypeEnum b : CalculationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CalculationTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CalculationTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CalculationTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CalculationTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CALCULATION_TYPE = "calculation_type";
  @SerializedName(SERIALIZED_NAME_CALCULATION_TYPE)
  private CalculationTypeEnum calculationType;

  public static final String SERIALIZED_NAME_WORK_WEEK_START = "work_week_start";
  @SerializedName(SERIALIZED_NAME_WORK_WEEK_START)
  private WeekDaysEnum workWeekStart;

  public static final String SERIALIZED_NAME_WORK_WEEK_END = "work_week_end";
  @SerializedName(SERIALIZED_NAME_WORK_WEEK_END)
  private WeekDaysEnum workWeekEnd;

  public EstimateFirstPaymentCompensationDetails() {
  }

  public EstimateFirstPaymentCompensationDetails amount(Double amount) {
    if (amount != null && amount < 0) {
      throw new IllegalArgumentException("Invalid value for amount. Must be greater than or equal to 0.");
    }
    
    
    
    this.amount = amount;
    return this;
  }

  public EstimateFirstPaymentCompensationDetails amount(Integer amount) {
    if (amount != null && amount < 0) {
      throw new IllegalArgumentException("Invalid value for amount. Must be greater than or equal to 0.");
    }
    
    
    
    this.amount = amount.doubleValue();
    return this;
  }

   /**
   * Amount to be paid. Must be a positive number.
   * minimum: 0
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2500", value = "Amount to be paid. Must be a positive number.")

  public Double getAmount() {
    return amount;
  }


  public void setAmount(Double amount) {
    if (amount != null && amount < 0) {
      throw new IllegalArgumentException("Invalid value for amount. Must be greater than or equal to 0.");
    }
    
    
    this.amount = amount;
  }


  public EstimateFirstPaymentCompensationDetails currencyCode(String currencyCode) {
    
    
    if (currencyCode != null && currencyCode.length() < 3) {
      throw new IllegalArgumentException("Invalid value for currencyCode. Length must be greater than or equal to 3.");
    }
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "GBP", value = "")

  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    
    
    if (currencyCode != null && currencyCode.length() < 3) {
      throw new IllegalArgumentException("Invalid value for currencyCode. Length must be greater than or equal to 3.");
    }
    this.currencyCode = currencyCode;
  }


  public EstimateFirstPaymentCompensationDetails scale(WorkStatementCycleScaleEnum scale) {
    
    
    
    
    this.scale = scale;
    return this;
  }

   /**
   * Get scale
   * @return scale
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WorkStatementCycleScaleEnum getScale() {
    return scale;
  }


  public void setScale(WorkStatementCycleScaleEnum scale) {
    
    
    
    this.scale = scale;
  }


  public EstimateFirstPaymentCompensationDetails cycleEnd(Double cycleEnd) {
    if (cycleEnd != null && cycleEnd < 1) {
      throw new IllegalArgumentException("Invalid value for cycleEnd. Must be greater than or equal to 1.");
    }
    if (cycleEnd != null && cycleEnd > 31) {
      throw new IllegalArgumentException("Invalid value for cycleEnd. Must be less than or equal to 31.");
    }
    
    
    this.cycleEnd = cycleEnd;
    return this;
  }

  public EstimateFirstPaymentCompensationDetails cycleEnd(Integer cycleEnd) {
    if (cycleEnd != null && cycleEnd < 1) {
      throw new IllegalArgumentException("Invalid value for cycleEnd. Must be greater than or equal to 1.");
    }
    if (cycleEnd != null && cycleEnd > 31) {
      throw new IllegalArgumentException("Invalid value for cycleEnd. Must be less than or equal to 31.");
    }
    
    
    this.cycleEnd = cycleEnd.doubleValue();
    return this;
  }

   /**
   * Date invoice cycle ends.
   * minimum: 1
   * maximum: 31
   * @return cycleEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date invoice cycle ends.")

  public Double getCycleEnd() {
    return cycleEnd;
  }


  public void setCycleEnd(Double cycleEnd) {
    if (cycleEnd != null && cycleEnd < 1) {
      throw new IllegalArgumentException("Invalid value for cycleEnd. Must be greater than or equal to 1.");
    }
    if (cycleEnd != null && cycleEnd > 31) {
      throw new IllegalArgumentException("Invalid value for cycleEnd. Must be less than or equal to 31.");
    }
    
    this.cycleEnd = cycleEnd;
  }


  public EstimateFirstPaymentCompensationDetails cycleEndType(WorkStatementCycleEndTypeEnum cycleEndType) {
    
    
    
    
    this.cycleEndType = cycleEndType;
    return this;
  }

   /**
   * Get cycleEndType
   * @return cycleEndType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WorkStatementCycleEndTypeEnum getCycleEndType() {
    return cycleEndType;
  }


  public void setCycleEndType(WorkStatementCycleEndTypeEnum cycleEndType) {
    
    
    
    this.cycleEndType = cycleEndType;
  }


  public EstimateFirstPaymentCompensationDetails paymentDueType(WorkStatementPaymentDueTypeEnum paymentDueType) {
    
    
    
    
    this.paymentDueType = paymentDueType;
    return this;
  }

   /**
   * Get paymentDueType
   * @return paymentDueType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WorkStatementPaymentDueTypeEnum getPaymentDueType() {
    return paymentDueType;
  }


  public void setPaymentDueType(WorkStatementPaymentDueTypeEnum paymentDueType) {
    
    
    
    this.paymentDueType = paymentDueType;
  }


  public EstimateFirstPaymentCompensationDetails paymentDueDays(Double paymentDueDays) {
    if (paymentDueDays != null && paymentDueDays < 0) {
      throw new IllegalArgumentException("Invalid value for paymentDueDays. Must be greater than or equal to 0.");
    }
    if (paymentDueDays != null && paymentDueDays > 90) {
      throw new IllegalArgumentException("Invalid value for paymentDueDays. Must be less than or equal to 90.");
    }
    
    
    this.paymentDueDays = paymentDueDays;
    return this;
  }

  public EstimateFirstPaymentCompensationDetails paymentDueDays(Integer paymentDueDays) {
    if (paymentDueDays != null && paymentDueDays < 0) {
      throw new IllegalArgumentException("Invalid value for paymentDueDays. Must be greater than or equal to 0.");
    }
    if (paymentDueDays != null && paymentDueDays > 90) {
      throw new IllegalArgumentException("Invalid value for paymentDueDays. Must be less than or equal to 90.");
    }
    
    
    this.paymentDueDays = paymentDueDays.doubleValue();
    return this;
  }

   /**
   * Get paymentDueDays
   * minimum: 0
   * maximum: 90
   * @return paymentDueDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getPaymentDueDays() {
    return paymentDueDays;
  }


  public void setPaymentDueDays(Double paymentDueDays) {
    if (paymentDueDays != null && paymentDueDays < 0) {
      throw new IllegalArgumentException("Invalid value for paymentDueDays. Must be greater than or equal to 0.");
    }
    if (paymentDueDays != null && paymentDueDays > 90) {
      throw new IllegalArgumentException("Invalid value for paymentDueDays. Must be less than or equal to 90.");
    }
    
    this.paymentDueDays = paymentDueDays;
  }


  public EstimateFirstPaymentCompensationDetails calculationType(CalculationTypeEnum calculationType) {
    
    
    
    
    this.calculationType = calculationType;
    return this;
  }

   /**
   * Either works days or calendar days
   * @return calculationType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Either works days or calendar days")

  public CalculationTypeEnum getCalculationType() {
    return calculationType;
  }


  public void setCalculationType(CalculationTypeEnum calculationType) {
    
    
    
    this.calculationType = calculationType;
  }


  public EstimateFirstPaymentCompensationDetails workWeekStart(WeekDaysEnum workWeekStart) {
    
    
    
    
    this.workWeekStart = workWeekStart;
    return this;
  }

   /**
   * Get workWeekStart
   * @return workWeekStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WeekDaysEnum getWorkWeekStart() {
    return workWeekStart;
  }


  public void setWorkWeekStart(WeekDaysEnum workWeekStart) {
    
    
    
    this.workWeekStart = workWeekStart;
  }


  public EstimateFirstPaymentCompensationDetails workWeekEnd(WeekDaysEnum workWeekEnd) {
    
    
    
    
    this.workWeekEnd = workWeekEnd;
    return this;
  }

   /**
   * Get workWeekEnd
   * @return workWeekEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WeekDaysEnum getWorkWeekEnd() {
    return workWeekEnd;
  }


  public void setWorkWeekEnd(WeekDaysEnum workWeekEnd) {
    
    
    
    this.workWeekEnd = workWeekEnd;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EstimateFirstPaymentCompensationDetails instance itself
   */
  public EstimateFirstPaymentCompensationDetails putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EstimateFirstPaymentCompensationDetails estimateFirstPaymentCompensationDetails = (EstimateFirstPaymentCompensationDetails) o;
    return Objects.equals(this.amount, estimateFirstPaymentCompensationDetails.amount) &&
        Objects.equals(this.currencyCode, estimateFirstPaymentCompensationDetails.currencyCode) &&
        Objects.equals(this.scale, estimateFirstPaymentCompensationDetails.scale) &&
        Objects.equals(this.cycleEnd, estimateFirstPaymentCompensationDetails.cycleEnd) &&
        Objects.equals(this.cycleEndType, estimateFirstPaymentCompensationDetails.cycleEndType) &&
        Objects.equals(this.paymentDueType, estimateFirstPaymentCompensationDetails.paymentDueType) &&
        Objects.equals(this.paymentDueDays, estimateFirstPaymentCompensationDetails.paymentDueDays) &&
        Objects.equals(this.calculationType, estimateFirstPaymentCompensationDetails.calculationType) &&
        Objects.equals(this.workWeekStart, estimateFirstPaymentCompensationDetails.workWeekStart) &&
        Objects.equals(this.workWeekEnd, estimateFirstPaymentCompensationDetails.workWeekEnd)&&
        Objects.equals(this.additionalProperties, estimateFirstPaymentCompensationDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, currencyCode, scale, cycleEnd, cycleEndType, paymentDueType, paymentDueDays, calculationType, workWeekStart, workWeekEnd, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EstimateFirstPaymentCompensationDetails {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    scale: ").append(toIndentedString(scale)).append("\n");
    sb.append("    cycleEnd: ").append(toIndentedString(cycleEnd)).append("\n");
    sb.append("    cycleEndType: ").append(toIndentedString(cycleEndType)).append("\n");
    sb.append("    paymentDueType: ").append(toIndentedString(paymentDueType)).append("\n");
    sb.append("    paymentDueDays: ").append(toIndentedString(paymentDueDays)).append("\n");
    sb.append("    calculationType: ").append(toIndentedString(calculationType)).append("\n");
    sb.append("    workWeekStart: ").append(toIndentedString(workWeekStart)).append("\n");
    sb.append("    workWeekEnd: ").append(toIndentedString(workWeekEnd)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("amount");
    openapiFields.add("currency_code");
    openapiFields.add("scale");
    openapiFields.add("cycle_end");
    openapiFields.add("cycle_end_type");
    openapiFields.add("payment_due_type");
    openapiFields.add("payment_due_days");
    openapiFields.add("calculation_type");
    openapiFields.add("work_week_start");
    openapiFields.add("work_week_end");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EstimateFirstPaymentCompensationDetails
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EstimateFirstPaymentCompensationDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EstimateFirstPaymentCompensationDetails is not found in the empty JSON string", EstimateFirstPaymentCompensationDetails.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("currency_code") != null && !jsonObj.get("currency_code").isJsonNull()) && !jsonObj.get("currency_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency_code").toString()));
      }
      if ((jsonObj.get("calculation_type") != null && !jsonObj.get("calculation_type").isJsonNull()) && !jsonObj.get("calculation_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `calculation_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("calculation_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EstimateFirstPaymentCompensationDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EstimateFirstPaymentCompensationDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EstimateFirstPaymentCompensationDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EstimateFirstPaymentCompensationDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<EstimateFirstPaymentCompensationDetails>() {
           @Override
           public void write(JsonWriter out, EstimateFirstPaymentCompensationDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EstimateFirstPaymentCompensationDetails read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EstimateFirstPaymentCompensationDetails instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EstimateFirstPaymentCompensationDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EstimateFirstPaymentCompensationDetails
  * @throws IOException if the JSON string is invalid with respect to EstimateFirstPaymentCompensationDetails
  */
  public static EstimateFirstPaymentCompensationDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EstimateFirstPaymentCompensationDetails.class);
  }

 /**
  * Convert an instance of EstimateFirstPaymentCompensationDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

